# .cargo/config
[build]
# Always compile for the instruction set of the STM32F1
target = "thumbv7m-none-eabi"

# use the Tlink.x scrip from the cortex-m-rt crate
[target.thumbv7m-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x", "-g"]


